# Generated by Django 3.1.7 on 2021-12-24 08:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20211224_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='postVoter', to=settings.AUTH_USER_MODEL),
        ),
    ]
