# Generated by Django 3.1.7 on 2021-12-24 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20211224_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='community',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.community'),
        ),
    ]
