# Generated by Django 3.1.7 on 2021-12-24 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20211224_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='community',
        ),
        migrations.AddField(
            model_name='community',
            name='thread',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='main.thread'),
            preserve_default=False,
        ),
    ]
