# Generated by Django 3.1.7 on 2021-12-24 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211224_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='thread',
        ),
        migrations.AddField(
            model_name='thread',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.community'),
        ),
    ]
