# Generated by Django 3.1.7 on 2022-01-03 15:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20211224_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
