# Generated by Django 3.1.7 on 2022-01-03 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_thread_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='community',
        ),
        migrations.AddField(
            model_name='thread',
            name='community',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.community'),
            preserve_default=False,
        ),
    ]
