# Generated by Django 3.1.7 on 2022-01-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220103_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='comment',
            field=models.ManyToManyField(blank=True, to='main.Comment'),
        ),
    ]
