# Generated by Django 3.1.7 on 2022-01-06 17:21

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20220105_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=tinymce.models.HTMLField(blank=True, default=None, null=True),
        ),
    ]
