# Generated by Django 3.1.7 on 2022-01-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20220107_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='post_image'),
        ),
    ]
