# Generated by Django 3.1.7 on 2022-01-06 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20220107_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='image',
            new_name='postImage',
        ),
    ]
