# Generated by Django 3.1.7 on 2022-01-06 18:16

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220107_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='postImage',
        ),
        migrations.AddField(
            model_name='thread',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, size=[50, 80], upload_to='post_image'),
        ),
    ]
