# Generated by Django 3.1.7 on 2022-01-07 03:35

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20220107_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default=None, force_format=None, keep_meta=True, null=True, quality=100, size=[1920, 1080], upload_to='post_image'),
        ),
    ]
