# Generated by Django 3.2.9 on 2021-12-11 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20211211_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userDownVotes',
            field=models.ManyToManyField(blank=True, related_name='threadDownVotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='userUpVotes',
            field=models.ManyToManyField(blank=True, related_name='threadUpVotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
