# Generated by Django 4.0 on 2021-12-14 17:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0008_auto_20211211_2204'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Thread',
        ),
    ]
