# Generated by Django 4.0 on 2021-12-17 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_comments_date_alter_thread_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='comments',
        ),
        migrations.AddField(
            model_name='thread',
            name='comments',
            field=models.ManyToManyField(to='main.Comments'),
        ),
    ]
