# Generated by Django 3.2.9 on 2021-12-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_thread_comments_thread_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='comments',
        ),
        migrations.AddField(
            model_name='thread',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.comments'),
        ),
    ]
