# Generated by Django 3.2.9 on 2021-12-18 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_comments_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='votes',
        ),
    ]
