# Generated by Django 3.2.9 on 2021-12-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_comments_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='thread',
        ),
    ]
